services:
 jupyter:
    container_name: jup
    build: .
    volumes:
      - ./ipnb:/home/jovyan/ipnb
      - ./jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
      - /usr/share/fonts/truetype:/usr/share/fonts/truetype
    ports:
      - 8888:8888
