services:
 jupyter:
    container_name: jup
    image: jupyter/datascience-notebook
    volumes:
      - ./ipnb:/home/jovyan/ipnb
      - ./jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
      - /usr/share/fonts/truetype:/usr/share/fonts/truetype
    ports:
      - 8888:8888
volumes:
  promdata: { }
  vmdata: { }
  grafanadata: { }
networks:
  vm_net:
